/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as DespesasRouteImport } from './routes/despesas'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as FechamentoCaixaRouteImport } from './routes/fechamento-caixa'
import { Route as FluxoCaixaRouteImport } from './routes/fluxo-caixa'
import { Route as FornecedoresRouteImport } from './routes/fornecedores'
import { Route as GuiaRouteImport } from './routes/guia'
import { Route as HistoricoClientesRouteImport } from './routes/historico-clientes'
import { Route as MetasRouteImport } from './routes/metas'
import { Route as OrdensRouteImport } from './routes/ordens'
import { Route as PdvRouteImport } from './routes/pdv'
import { Route as PrecificacaoRouteImport } from './routes/precificacao'
import { Route as RelatorioEstoqueRouteImport } from './routes/relatorio-estoque'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TecnicosRouteImport } from './routes/tecnicos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DespesasRoute = DespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const FechamentoCaixaRoute = FechamentoCaixaRouteImport.update({
  id: '/fechamento-caixa',
  path: '/fechamento-caixa',
  getParentRoute: () => rootRouteImport,
} as any)
const FluxoCaixaRoute = FluxoCaixaRouteImport.update({
  id: '/fluxo-caixa',
  path: '/fluxo-caixa',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedoresRoute = FornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaRoute = GuiaRouteImport.update({
  id: '/guia',
  path: '/guia',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoClientesRoute = HistoricoClientesRouteImport.update({
  id: '/historico-clientes',
  path: '/historico-clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const MetasRoute = MetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdensRoute = OrdensRouteImport.update({
  id: '/ordens',
  path: '/ordens',
  getParentRoute: () => rootRouteImport,
} as any)
const PdvRoute = PdvRouteImport.update({
  id: '/pdv',
  path: '/pdv',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecificacaoRoute = PrecificacaoRouteImport.update({
  id: '/precificacao',
  path: '/precificacao',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatorioEstoqueRoute = RelatorioEstoqueRouteImport.update({
  id: '/relatorio-estoque',
  path: '/relatorio-estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TecnicosRoute = TecnicosRouteImport.update({
  id: '/tecnicos',
  path: '/tecnicos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/despesas': typeof DespesasRoute
  '/estoque': typeof EstoqueRoute
  '/fechamento-caixa': typeof FechamentoCaixaRoute
  '/fluxo-caixa': typeof FluxoCaixaRoute
  '/fornecedores': typeof FornecedoresRoute
  '/guia': typeof GuiaRoute
  '/historico-clientes': typeof HistoricoClientesRoute
  '/metas': typeof MetasRoute
  '/ordens': typeof OrdensRoute
  '/pdv': typeof PdvRoute
  '/precificacao': typeof PrecificacaoRoute
  '/relatorio-estoque': typeof RelatorioEstoqueRoute
  '/relatorios': typeof RelatoriosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tecnicos': typeof TecnicosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/despesas': typeof DespesasRoute
  '/estoque': typeof EstoqueRoute
  '/fechamento-caixa': typeof FechamentoCaixaRoute
  '/fluxo-caixa': typeof FluxoCaixaRoute
  '/fornecedores': typeof FornecedoresRoute
  '/guia': typeof GuiaRoute
  '/historico-clientes': typeof HistoricoClientesRoute
  '/metas': typeof MetasRoute
  '/ordens': typeof OrdensRoute
  '/pdv': typeof PdvRoute
  '/precificacao': typeof PrecificacaoRoute
  '/relatorio-estoque': typeof RelatorioEstoqueRoute
  '/relatorios': typeof RelatoriosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tecnicos': typeof TecnicosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/despesas': typeof DespesasRoute
  '/estoque': typeof EstoqueRoute
  '/fechamento-caixa': typeof FechamentoCaixaRoute
  '/fluxo-caixa': typeof FluxoCaixaRoute
  '/fornecedores': typeof FornecedoresRoute
  '/guia': typeof GuiaRoute
  '/historico-clientes': typeof HistoricoClientesRoute
  '/metas': typeof MetasRoute
  '/ordens': typeof OrdensRoute
  '/pdv': typeof PdvRoute
  '/precificacao': typeof PrecificacaoRoute
  '/relatorio-estoque': typeof RelatorioEstoqueRoute
  '/relatorios': typeof RelatoriosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tecnicos': typeof TecnicosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/clientes'
    | '/configuracoes'
    | '/despesas'
    | '/estoque'
    | '/fechamento-caixa'
    | '/fluxo-caixa'
    | '/fornecedores'
    | '/guia'
    | '/historico-clientes'
    | '/metas'
    | '/ordens'
    | '/pdv'
    | '/precificacao'
    | '/relatorio-estoque'
    | '/relatorios'
    | '/reset-password'
    | '/tecnicos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/clientes'
    | '/configuracoes'
    | '/despesas'
    | '/estoque'
    | '/fechamento-caixa'
    | '/fluxo-caixa'
    | '/fornecedores'
    | '/guia'
    | '/historico-clientes'
    | '/metas'
    | '/ordens'
    | '/pdv'
    | '/precificacao'
    | '/relatorio-estoque'
    | '/relatorios'
    | '/reset-password'
    | '/tecnicos'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/clientes'
    | '/configuracoes'
    | '/despesas'
    | '/estoque'
    | '/fechamento-caixa'
    | '/fluxo-caixa'
    | '/fornecedores'
    | '/guia'
    | '/historico-clientes'
    | '/metas'
    | '/ordens'
    | '/pdv'
    | '/precificacao'
    | '/relatorio-estoque'
    | '/relatorios'
    | '/reset-password'
    | '/tecnicos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ClientesRoute: typeof ClientesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DespesasRoute: typeof DespesasRoute
  EstoqueRoute: typeof EstoqueRoute
  FechamentoCaixaRoute: typeof FechamentoCaixaRoute
  FluxoCaixaRoute: typeof FluxoCaixaRoute
  FornecedoresRoute: typeof FornecedoresRoute
  GuiaRoute: typeof GuiaRoute
  HistoricoClientesRoute: typeof HistoricoClientesRoute
  MetasRoute: typeof MetasRoute
  OrdensRoute: typeof OrdensRoute
  PdvRoute: typeof PdvRoute
  PrecificacaoRoute: typeof PrecificacaoRoute
  RelatorioEstoqueRoute: typeof RelatorioEstoqueRoute
  RelatoriosRoute: typeof RelatoriosRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TecnicosRoute: typeof TecnicosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despesas': {
      id: '/despesas'
      path: '/despesas'
      fullPath: '/despesas'
      preLoaderRoute: typeof DespesasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fechamento-caixa': {
      id: '/fechamento-caixa'
      path: '/fechamento-caixa'
      fullPath: '/fechamento-caixa'
      preLoaderRoute: typeof FechamentoCaixaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fluxo-caixa': {
      id: '/fluxo-caixa'
      path: '/fluxo-caixa'
      fullPath: '/fluxo-caixa'
      preLoaderRoute: typeof FluxoCaixaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedores': {
      id: '/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof FornecedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia': {
      id: '/guia'
      path: '/guia'
      fullPath: '/guia'
      preLoaderRoute: typeof GuiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico-clientes': {
      id: '/historico-clientes'
      path: '/historico-clientes'
      fullPath: '/historico-clientes'
      preLoaderRoute: typeof HistoricoClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metas': {
      id: '/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof MetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ordens': {
      id: '/ordens'
      path: '/ordens'
      fullPath: '/ordens'
      preLoaderRoute: typeof OrdensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdv': {
      id: '/pdv'
      path: '/pdv'
      fullPath: '/pdv'
      preLoaderRoute: typeof PdvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precificacao': {
      id: '/precificacao'
      path: '/precificacao'
      fullPath: '/precificacao'
      preLoaderRoute: typeof PrecificacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorio-estoque': {
      id: '/relatorio-estoque'
      path: '/relatorio-estoque'
      fullPath: '/relatorio-estoque'
      preLoaderRoute: typeof RelatorioEstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tecnicos': {
      id: '/tecnicos'
      path: '/tecnicos'
      fullPath: '/tecnicos'
      preLoaderRoute: typeof TecnicosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ClientesRoute: ClientesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DespesasRoute: DespesasRoute,
  EstoqueRoute: EstoqueRoute,
  FechamentoCaixaRoute: FechamentoCaixaRoute,
  FluxoCaixaRoute: FluxoCaixaRoute,
  FornecedoresRoute: FornecedoresRoute,
  GuiaRoute: GuiaRoute,
  HistoricoClientesRoute: HistoricoClientesRoute,
  MetasRoute: MetasRoute,
  OrdensRoute: OrdensRoute,
  PdvRoute: PdvRoute,
  PrecificacaoRoute: PrecificacaoRoute,
  RelatorioEstoqueRoute: RelatorioEstoqueRoute,
  RelatoriosRoute: RelatoriosRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TecnicosRoute: TecnicosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
